spring.application.name=realtime-service
server.port=8089

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=orioneta
spring.rabbitmq.password=orioneta

management.endpoints.web.exposure.include=health,info
