apiVersion: v1
kind: Secret
metadata:
  name: orioneta-secrets
  namespace: orioneta
type: Opaque
stringData:
  POSTGRES_USER: orioneta
  POSTGRES_PASSWORD: Orioneta2024!
  POSTGRES_DB: orioneta
  RABBITMQ_DEFAULT_USER: orioneta
  RABBITMQ_DEFAULT_PASS: Rabbit2024!
  REDIS_PASSWORD: Redis2024!
  JWT_SECRET: OrionetaSuperSecretJWT2024KeyMinimo32Chars!!
