server:
  port: 8084

spring:
  application:
    name: friendship-service

  datasource:
    url: jdbc:postgresql://localhost:5432/orioneta_friendships
    username: orioneta
    password: orioneta

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: orioneta
    password: orioneta

orioneta:
  services:
    users: http://localhost:8083
    conversations: http://localhost:8085

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,loggers
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

logging:
  level:
    root: INFO
    org.springframework: WARN
    org.hibernate: WARN
    cl.orioneta: DEBUG
