spring.application.name=message-service
server.port=8086

spring.datasource.url=jdbc:postgresql://localhost:5432/orioneta_messages
spring.datasource.username=orioneta
spring.datasource.password=orioneta

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=orioneta
spring.rabbitmq.password=orioneta

management.endpoints.web.exposure.include=health,info
