apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../k8s
  - local-path-provisioner.yaml

patches:
  - target:
      kind: StorageClass
      name: ebs-gp3
    patch: |-
      - op: replace
        path: /provisioner
        value: rancher.io/local-path
      - op: remove
        path: /parameters
  - target:
      kind: Service
      name: gateway-service
    patch: |-
      - op: remove
        path: /spec/loadBalancerClass
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/startupProbe
        value:
          httpGet:
            path: /actuator/health/liveness
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30

images:
  - name: docker.io/oriontheprogrammer/orioneta-gateway-service
    newTag: latest
  - name: docker.io/oriontheprogrammer/orioneta-bff-service
    newTag: latest
  - name: docker.io/oriontheprogrammer/orioneta-auth-service
    newTag: latest
  - name: docker.io/oriontheprogrammer/orioneta-user-service
    newTag: latest
  - name: docker.io/oriontheprogrammer/orioneta-friendship-service
    newTag: latest
  - name: docker.io/oriontheprogrammer/orioneta-conversation-service
    newTag: latest
  - name: docker.io/oriontheprogrammer/orioneta-message-service
    newTag: latest
  - name: docker.io/oriontheprogrammer/orioneta-notification-service
    newTag: latest
  - name: docker.io/oriontheprogrammer/orioneta-customization-service
    newTag: latest
  - name: docker.io/oriontheprogrammer/orioneta-media-service
    newTag: latest
  - name: docker.io/oriontheprogrammer/orioneta-neta-market-service
    newTag: latest
  - name: docker.io/oriontheprogrammer/orioneta-realtime-service
    newTag: latest
  - name: docker.io/oriontheprogrammer/orioneta-moderation-service
    newTag: latest
  - name: docker.io/oriontheprogrammer/orioneta-audit-service
    newTag: latest
