spring.application.name=bff-service
server.port=8081

orioneta.services.auth=http://localhost:8082
orioneta.services.users=http://localhost:8083
orioneta.services.friendships=http://localhost:8084
orioneta.services.conversations=http://localhost:8085
orioneta.services.messages=http://localhost:8086
orioneta.services.notifications=http://localhost:8087
orioneta.services.media=http://localhost:8088
orioneta.services.customizations=http://localhost:8091
orioneta.services.neta-market=http://localhost:8092

management.endpoints.web.exposure.include=health,info,metrics,prometheus,loggers
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true

logging.level.root=INFO
logging.level.org.springframework=WARN
logging.level.org.hibernate.SQL=WARN
logging.level.org.hibernate.type.descriptor.sql=WARN
logging.level.cl.orioneta=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n
