spring.application.name=gateway-service
server.port=8080

management.endpoints.web.exposure.include=health,info

orioneta.routes.auth=http://localhost:8082
orioneta.routes.users=http://localhost:8083
orioneta.routes.contacts=http://localhost:8084
orioneta.routes.conversations=http://localhost:8085
orioneta.routes.messages=http://localhost:8086
orioneta.routes.notifications=http://localhost:8087
orioneta.routes.media=http://localhost:8088
orioneta.routes.realtime=http://localhost:8089
orioneta.routes.audit=http://localhost:8090
orioneta.routes.bff=http://localhost:8081
