spring.application.name=gateway-service
server.port=8080

management.endpoints.web.exposure.include=health,info,metrics,prometheus,loggers
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true

logging.level.root=INFO
logging.level.org.springframework=WARN
logging.level.org.hibernate.SQL=WARN
logging.level.org.hibernate.type.descriptor.sql=WARN
logging.level.cl.orioneta=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n

orioneta.routes.auth=http://localhost:8082
orioneta.routes.users=http://localhost:8083
orioneta.routes.friendships=http://localhost:8084
orioneta.routes.conversations=http://localhost:8085
orioneta.routes.messages=http://localhost:8086
orioneta.routes.notifications=http://localhost:8087
orioneta.routes.customizations=http://localhost:8088
orioneta.routes.media=http://localhost:8089
orioneta.routes.neta-market=http://localhost:8090
orioneta.routes.realtime=http://localhost:8091
orioneta.routes.moderation=http://localhost:8092
orioneta.routes.audit=http://localhost:8093
orioneta.routes.bff=http://localhost:8081
