spring.application.name=media-service
server.port=8088

spring.datasource.url=jdbc:postgresql://localhost:5432/orioneta_media
spring.datasource.username=orioneta
spring.datasource.password=orioneta

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

management.endpoints.web.exposure.include=health,info
