package cl.orioneta.users.domain.model;

import cl.orioneta.users.domain.exception.UserGlobalException;
import java.time.LocalDateTime;
import java.util.Objects;

/**
 * Represents the public identity profile of an Orioneta user.
 *
 * <p>This is a domain model, not a JPA entity. It keeps the business rules that
 * must remain true regardless of whether the user is created from a REST
 * request, a database adapter, a test fixture or a future event consumer. Future
 * persistence changes should map to and from this class instead of moving these
 * validations into controllers or entities.
 */
public class User {

    private static final int MAX_BIO_LENGTH = 160;
    private static final int FRIEND_CODE_LENGTH = 8;

    private final UserID id;
    private final String username;
    private final String email;
    private final String friendCode;
    private final LocalDateTime createdAt;

    private String displayName;
    private String avatarUrl;
    private String bannerUrl;
    private String bio;
    private UserStatus status;
    private AccountVisibility accountVisibility;
    private LocalDateTime updatedAt;

    /**
     * Creates a user profile using the required fields for the current signup
     * flow.
     *
     * <p>The friend code is generated immediately because it is part of the
     * public identity used by {@code friendship-service}. A persistence adapter
     * should still enforce uniqueness at database level before saving.
     *
     * @param username unique username selected by the user
     * @param displayName visible name shown in chats and profiles
     * @param email email associated with the user identity
     * @param avatarUrl optional avatar URL
     * @param status initial presence status
     */
    public User(String username, String displayName, String email, String avatarUrl, UserStatus status) {
        this(
                new UserID(),
                username,
                displayName,
                email,
                FriendCodeGenerator.generate(),
                avatarUrl,
                null,
                "",
                status,
                AccountVisibility.PUBLIC,
                LocalDateTime.now(),
                LocalDateTime.now()
        );
    }

    /**
     * Backward-compatible constructor for the first local version of the model.
     *
     * <p>The old prototype received a phone number and {@code profileimageurl}.
     * Phone is no longer part of the user identity in the updated architecture,
     * so it is intentionally ignored here. The old profile image value maps to
     * the new avatar field.
     *
     * @param username unique username selected by the user
     * @param displayName visible name shown in chats and profiles
     * @param email email associated with the user identity
     * @param phoneNumber legacy field, no longer stored in this domain model
     * @param profileImageUrl legacy avatar URL field
     * @param status initial presence status
     */
    public User(
            String username,
            String displayName,
            String email,
            String phoneNumber,
            String profileImageUrl,
            UserStatus status
    ) {
        this(username, displayName, email, profileImageUrl, status);
    }

    /**
     * Rehydrates a user that already exists in persistence.
     *
     * <p>Use this constructor from adapters when loading rows from the database.
     * It accepts all fields explicitly so historical timestamps and identifiers
     * are not regenerated by accident.
     *
     * @param id internal immutable user identifier
     * @param username unique username selected by the user
     * @param displayName visible name shown in chats and profiles
     * @param email email associated with the user identity
     * @param friendCode public hexadecimal code used to add friends
     * @param avatarUrl optional avatar URL
     * @param bannerUrl optional profile banner URL
     * @param bio short public biography
     * @param status current presence status
     * @param accountVisibility profile discoverability setting
     * @param createdAt creation timestamp
     * @param updatedAt last update timestamp
     */
    public User(
            UserID id,
            String username,
            String displayName,
            String email,
            String friendCode,
            String avatarUrl,
            String bannerUrl,
            String bio,
            UserStatus status,
            AccountVisibility accountVisibility,
            LocalDateTime createdAt,
            LocalDateTime updatedAt
    ) {
        this.id = Objects.requireNonNull(id, "El id del usuario es obligatorio.");
        this.username = requireText(username, "El username no puede ser nulo, vacio o contener solo espacios.");
        this.displayName = requireText(displayName, "El displayName no puede ser nulo, vacio o contener solo espacios.");
        this.email = requireText(email, "El email no puede ser nulo, vacio o contener solo espacios.");
        this.friendCode = validateFriendCode(friendCode);
        this.avatarUrl = normalizeOptionalText(avatarUrl);
        this.bannerUrl = normalizeOptionalText(bannerUrl);
        this.bio = validateBio(bio);
        this.status = defaultStatus(status);
        this.accountVisibility = defaultVisibility(accountVisibility);
        this.createdAt = Objects.requireNonNull(createdAt, "La fecha de creacion es obligatoria.");
        this.updatedAt = Objects.requireNonNull(updatedAt, "La fecha de actualizacion es obligatoria.");
    }

    /**
     * Updates public profile fields that can change after registration.
     *
     * <p>Username, email, id and friend code are intentionally immutable in this
     * model because changing them affects authentication, search and friendship
     * flows. Add dedicated methods later if the product needs those changes.
     *
     * @param displayName new visible name
     * @param avatarUrl new avatar URL, nullable when the user removes it
     * @param bannerUrl new banner URL, nullable when the user removes it
     * @param bio new biography, nullable or blank when the user clears it
     */
    public void updateProfile(String displayName, String avatarUrl, String bannerUrl, String bio) {
        this.displayName = requireText(displayName, "El displayName no puede ser nulo, vacio o contener solo espacios.");
        this.avatarUrl = normalizeOptionalText(avatarUrl);
        this.bannerUrl = normalizeOptionalText(bannerUrl);
        this.bio = validateBio(bio);
        touch();
    }

    /**
     * Backward-compatible profile update used by the first prototype.
     *
     * @param displayName new visible name
     * @param profileImageUrl legacy avatar URL field
     */
    public void updateProfile(String displayName, String profileImageUrl) {
        updateProfile(displayName, profileImageUrl, bannerUrl, bio);
    }

    /**
     * Updates the user's presence status.
     *
     * <p>This method only changes the domain state. Publishing presence events is
     * the responsibility of an application use case or infrastructure adapter.
     *
     * @param status new presence status
     */
    public void updateStatus(UserStatus status) {
        this.status = Objects.requireNonNull(status, "El estado del usuario es obligatorio.");
        touch();
    }

    /**
     * Changes whether the user can be discovered by other users.
     *
     * @param accountVisibility new visibility preference
     */
    public void changeAccountVisibility(AccountVisibility accountVisibility) {
        this.accountVisibility = Objects.requireNonNull(
                accountVisibility,
                "La visibilidad de la cuenta es obligatoria."
        );
        touch();
    }

    /**
     * Returns the internal user identifier used by persistence and events.
     *
     * @return immutable user id
     */
    public UserID getId() {
        return id;
    }

    /**
     * Returns the unique username chosen by the user.
     *
     * @return unique username
     */
    public String getUsername() {
        return username;
    }

    /**
     * Returns the visible name shown in chats, groups and profiles.
     *
     * @return display name
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * Legacy getter kept temporarily while older code migrates to
     * {@link #getDisplayName()}.
     *
     * @return visible display name
     */
    @Deprecated(forRemoval = false)
    public String getDisplayname() {
        return displayName;
    }

    /**
     * Returns the email linked to the public profile.
     *
     * <p>This value helps connect {@code auth-service} identity data with the
     * user profile. Avoid exposing it publicly unless the API endpoint is meant
     * for the authenticated owner or internal services.
     *
     * @return profile email
     */
    public String getEmail() {
        return email;
    }

    /**
     * Returns the public hexadecimal code used by friendship flows.
     *
     * @return friend code such as {@code A91F23C7}
     */
    public String getFriendCode() {
        return friendCode;
    }

    /**
     * Returns the avatar URL shown in profile and chat surfaces.
     *
     * @return avatar URL or null when none is configured
     */
    public String getAvatarUrl() {
        return avatarUrl;
    }

    /**
     * Legacy getter kept temporarily while older code migrates to
     * {@link #getAvatarUrl()}.
     *
     * @return avatar URL
     */
    @Deprecated(forRemoval = false)
    public String getProfileimageurl() {
        return avatarUrl;
    }

    /**
     * Returns the profile banner URL.
     *
     * @return banner URL or null when none is configured
     */
    public String getBannerUrl() {
        return bannerUrl;
    }

    /**
     * Returns the short public biography.
     *
     * @return biography text, empty when the user has not configured one
     */
    public String getBio() {
        return bio;
    }

    /**
     * Returns the current presence state.
     *
     * @return user status
     */
    public UserStatus getStatus() {
        return status;
    }

    /**
     * Returns the account discoverability setting.
     *
     * @return account visibility
     */
    public AccountVisibility getAccountVisibility() {
        return accountVisibility;
    }

    /**
     * Returns when the user profile was created.
     *
     * @return creation timestamp
     */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * Returns when the user profile was last updated.
     *
     * @return last update timestamp
     */
    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    /**
     * Returns a compact representation useful for logs and debugging.
     *
     * @return readable user representation
     */
    @Override
    public String toString() {
        return "User{"
                + "id=" + id.getValue()
                + ", username='" + username + '\''
                + ", displayName='" + displayName + '\''
                + ", email='" + email + '\''
                + ", friendCode='" + friendCode + '\''
                + ", status=" + status
                + ", accountVisibility=" + accountVisibility
                + ", createdAt=" + createdAt
                + ", updatedAt=" + updatedAt
                + '}';
    }

    private void touch() {
        updatedAt = LocalDateTime.now();
    }

    private static UserStatus defaultStatus(UserStatus status) {
        return status == null ? UserStatus.OFFLINE : status;
    }

    private static AccountVisibility defaultVisibility(AccountVisibility visibility) {
        return visibility == null ? AccountVisibility.PUBLIC : visibility;
    }

    private static String requireText(String value, String errorMessage) {
        if (value == null || value.isBlank()) {
            throw new UserGlobalException(errorMessage);
        }
        return value.trim();
    }

    private static String normalizeOptionalText(String value) {
        if (value == null || value.isBlank()) {
            return null;
        }
        return value.trim();
    }

    private static String validateBio(String value) {
        if (value == null || value.isBlank()) {
            return "";
        }
        String normalized = value.trim();
        if (normalized.length() > MAX_BIO_LENGTH) {
            throw new UserGlobalException("La bio no puede superar " + MAX_BIO_LENGTH + " caracteres.");
        }
        return normalized;
    }

    private static String validateFriendCode(String value) {
        String normalized = requireText(value, "El friendCode es obligatorio.").toUpperCase();
        if (!normalized.matches("[0-9A-F]{" + FRIEND_CODE_LENGTH + "}")) {
            throw new UserGlobalException(
                    "El friendCode debe ser hexadecimal y tener "
                            + FRIEND_CODE_LENGTH
                            + " caracteres."
            );
        }
        return normalized;
    }
}
